/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author demia
 */
public class FRNMain extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FRNMain.class.getName());

    /**
     * Creates new form FRNMain
     */
    public FRNMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pane = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnTransaccion = new javax.swing.JButton();
        btnHistorial = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        btnMeta = new javax.swing.JButton();
        lblBienvenido = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnNavInicio = new javax.swing.JButton();
        btnNavTransaccion = new javax.swing.JButton();
        btnNavMeta = new javax.swing.JButton();
        btnNavHistorial = new javax.swing.JButton();
        btnNavPerfil = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pane.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(4, 57, 36));

        btnTransaccion.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        btnTransaccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-transacción-32.png"))); // NOI18N
        btnTransaccion.setText("Transaccion");
        btnTransaccion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTransaccion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnTransaccion.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnTransaccion.setIconTextGap(160);
        btnTransaccion.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        btnHistorial.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        btnHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-pasado-30.png"))); // NOI18N
        btnHistorial.setText("Historial");
        btnHistorial.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHistorial.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnHistorial.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnHistorial.setIconTextGap(190);
        btnHistorial.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        btnPerfil.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        btnPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-usuario-24 (1).png"))); // NOI18N
        btnPerfil.setText("Perfil");
        btnPerfil.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPerfil.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnPerfil.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnPerfil.setIconTextGap(210);
        btnPerfil.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        btnMeta.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        btnMeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-bandera-de-llegada-24.png"))); // NOI18N
        btnMeta.setText("Meta de ahorro");
        btnMeta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMeta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnMeta.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnMeta.setIconTextGap(130);
        btnMeta.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMeta, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMeta, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        lblBienvenido.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        lblBienvenido.setText("Bienvenido +USERNAME");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(4, 57, 36));

        btnNavInicio.setBackground(new java.awt.Color(4, 57, 36));
        btnNavInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-casa-28.png"))); // NOI18N
        btnNavInicio.setBorder(null);
        btnNavInicio.setBorderPainted(false);
        btnNavInicio.setFocusPainted(false);
        btnNavInicio.addActionListener(this::btnNavInicioActionPerformed);

        btnNavTransaccion.setBackground(new java.awt.Color(4, 57, 36));
        btnNavTransaccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-transferencia-de-dinero-28.png"))); // NOI18N
        btnNavTransaccion.setBorder(null);
        btnNavTransaccion.setBorderPainted(false);
        btnNavTransaccion.setFocusPainted(false);

        btnNavMeta.setBackground(new java.awt.Color(4, 57, 36));
        btnNavMeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-bandera-de-llegada-24_1.png"))); // NOI18N
        btnNavMeta.setBorder(null);
        btnNavMeta.setBorderPainted(false);
        btnNavMeta.setFocusPainted(false);

        btnNavHistorial.setBackground(new java.awt.Color(4, 57, 36));
        btnNavHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-pasado-24.png"))); // NOI18N
        btnNavHistorial.setBorder(null);
        btnNavHistorial.setBorderPainted(false);
        btnNavHistorial.setFocusPainted(false);

        btnNavPerfil.setBackground(new java.awt.Color(4, 57, 36));
        btnNavPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-configuración-24.png"))); // NOI18N
        btnNavPerfil.setBorder(null);
        btnNavPerfil.setBorderPainted(false);
        btnNavPerfil.setFocusPainted(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNavPerfil)
                    .addComponent(btnNavHistorial)
                    .addComponent(btnNavMeta)
                    .addComponent(btnNavTransaccion)
                    .addComponent(btnNavInicio))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnNavInicio)
                .addGap(53, 53, 53)
                .addComponent(btnNavTransaccion)
                .addGap(49, 49, 49)
                .addComponent(btnNavMeta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNavHistorial)
                .addGap(52, 52, 52)
                .addComponent(btnNavPerfil)
                .addGap(40, 40, 40))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoOf__1_-removebg-preview (1).png"))); // NOI18N

        javax.swing.GroupLayout paneLayout = new javax.swing.GroupLayout(pane);
        pane.setLayout(paneLayout);
        paneLayout.setHorizontalGroup(
            paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(lblBienvenido)
                        .addGap(461, 461, 461)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        paneLayout.setVerticalGroup(
            paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneLayout.createSequentialGroup()
                .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblBienvenido))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addGap(18, 18, 18)
                .addGroup(paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNavInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNavInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FRNMain().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnHistorial;
    public javax.swing.JButton btnMeta;
    public javax.swing.JButton btnNavHistorial;
    public javax.swing.JButton btnNavInicio;
    public javax.swing.JButton btnNavMeta;
    public javax.swing.JButton btnNavPerfil;
    public javax.swing.JButton btnNavTransaccion;
    public javax.swing.JButton btnPerfil;
    public javax.swing.JButton btnTransaccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JLabel lblBienvenido;
    public javax.swing.JPanel pane;
    // End of variables declaration//GEN-END:variables
}
